[server]
headless = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false

[theme]
primaryColor = "#1a5276"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f3f4"
textColor = "#1a252f"
